require("dotenv").config();

module.exports = {
  env: {
    API_URL: process.env.API_URL,
    FIREBASE_API_URL: process.env.FIREBASE_API_URL,
    FIREBASE_REF_DATETIME: process.env.FIREBASE_REF_DATETIME,
    FIREBASE_API_TYPE: process.env.FIREBASE_API_TYPE,
    FIREBASE_API_PROJECT_ID: process.env.FIREBASE_API_PROJECT_ID,
    FIREBASE_API_PRIVATE_KEY_ID: process.env.FIREBASE_API_PRIVATE_KEY_ID,
    FIREBASE_API_PRIVATE_KEY: process.env.FIREBASE_API_PRIVATE_KEY,
    FIREBASE_API_CLIENT_EMAIL: process.env.FIREBASE_API_CLIENT_EMAIL,
    FIREBASE_API_CLIENT_ID: process.env.FIREBASE_API_CLIENT_ID,
    FIREBASE_API_AUTH_URI: process.env.FIREBASE_API_AUTH_URI,
    FIREBASE_API_TOKEN_URI: process.env.FIREBASE_API_TOKEN_URI,
    FIREBASE_API_AUTH_PROVIDER_X509_CERT_URL:
      process.env.FIREBASE_API_AUTH_PROVIDER_X509_CERT_URL,
    FIREBASE_API_CLIENT_X509_CERT_URL:
      process.env.FIREBASE_API_CLIENT_X509_CERT_URL,
  },
};
